<?xml version="1.0"?>
<!DOCTYPE eparcel [ 
<!-- EVERY REQUEST CONTAIN THE eparcel TAG -->
<!ELEMENT eparcel (ratesAndServicesResponse)>

<!-- *********************************************************  -->
<!-- * Standard response for request for rates and services  *  -->
<!-- *********************************************************  -->
<!ELEMENT ratesAndServicesResponse (statusCode,  
												statusMessage+, 
												requestID, 
												handling, 
												language,
												product+, 
												packing*, 
												emptySpace*, 
												shippingOptions, 
												comment,
												nearestPostalOutlet*)>

	<!ELEMENT statusCode (#PCDATA)>
	<!ELEMENT statusMessage (#PCDATA)>
	<!ELEMENT requestID (#PCDATA)>
	<!ELEMENT handling (#PCDATA)>
	<!ELEMENT language (#PCDATA)>

	<!ELEMENT product (name, rate, shippingDate, deliveryDate, deliveryDayOfWeek, nextDayAM?, packingID)>
		<!ATTLIST product       id    CDATA    #REQUIRED>
		<!ATTLIST product       sequence    CDATA    #REQUIRED>
  		<!ELEMENT name (#PCDATA)>
		<!ELEMENT rate (#PCDATA)>
		<!ELEMENT shippingDate (#PCDATA)>
		<!ELEMENT deliveryDate (#PCDATA)>
		<!ELEMENT deliveryDayOfWeek (#PCDATA)>
		<!ELEMENT nextDayAM (#PCDATA)>
		<!ELEMENT packingID (#PCDATA)>

	<!ELEMENT packing (packingID, box+)>
		<!ELEMENT box (name, weight, expediterWeight, length, width, height, packedItem+)>
			<!ELEMENT weight (#PCDATA)>
			<!ELEMENT expediterWeight (#PCDATA)>
			<!ELEMENT length (#PCDATA)>
			<!ELEMENT width (#PCDATA)>
			<!ELEMENT height (#PCDATA)>
			<!ELEMENT packedItem (quantity, description)>
				<!ELEMENT quantity (#PCDATA)>
				<!ELEMENT description (#PCDATA)>

	<!ELEMENT emptySpace (length, width, height, weight)>

	<!ELEMENT shippingOptions (insurance, 
										deliveryConfirmation, 
										signature, 
										flexiblePaymentAvailable?)>
		<!ELEMENT insurance (#PCDATA)>
		<!ELEMENT deliveryConfirmation (#PCDATA)>
		<!ELEMENT signature (#PCDATA)>
		<!ELEMENT flexiblePaymentAvailable EMPTY>
												

	<!ELEMENT comment (#PCDATA)>


	<!-- *********************************************************  -->
	<!-- * 'nearestPostalOutlet'  is optional and is returned    *  -->
	<!-- * only if the merchant profile has this option enabled  *  -->
	<!-- *********************************************************  -->
	<!ELEMENT nearestPostalOutlet (postalOutletSequenceNo,
											distance,
										   outletName, 
											businessName , 
											postalAddress, 
											phoneNumber, 
											businessHours+)>
		<!ELEMENT postalOutletSequenceNo		(#PCDATA)>
		<!ELEMENT distance 			(#PCDATA)>
		<!ELEMENT outletName 		(#PCDATA)>
		<!ELEMENT businessName 		(#PCDATA)>
		<!ELEMENT postalAddress (addressLine+, postalCode , municipality)>
			<!ELEMENT addressLine 		(#PCDATA)>
			<!ELEMENT postalCode 		(#PCDATA)>
			<!ELEMENT municipality 		(#PCDATA)>
		<!ELEMENT phoneNumber 		(#PCDATA)>
		<!ELEMENT businessHours (dayId, dayOfWeek, time)>
			<!ELEMENT dayId     					(#PCDATA)>
			<!ELEMENT dayOfWeek 					(#PCDATA)>
			<!ELEMENT time 						(#PCDATA)>


]>
<eparcel>
	<ratesAndServicesResponse>
		
		<statusCode>1</statusCode>
		<statusMessage>OK</statusMessage>
		<requestID>46331</requestID>
		<handling>0.0</handling>
		<language>0</language>
		<product id="1040" sequence="1">
			<name>Priority Courier</name>
			<rate>255.26</rate>
			<shippingDate>2003-10-01</shippingDate>
			<deliveryDate>2003-10-02</deliveryDate>
			<deliveryDayOfWeek>5</deliveryDayOfWeek>
			<nextDayAM>true</nextDayAM>
			<packingID>P_0</packingID>
		</product>
		<product id="1030" sequence="2">
			<name>Xpresspost</name>
			<rate>171.01</rate>
			<shippingDate>2003-10-01</shippingDate>
			<deliveryDate>2003-10-02</deliveryDate>
			<deliveryDayOfWeek>5</deliveryDayOfWeek>
			<nextDayAM>false</nextDayAM>
			<packingID>P_0</packingID>
		</product>
		<product id="1010" sequence="3">
			<name>Regular</name>
			<rate>149.63</rate>
			<shippingDate>2003-10-01</shippingDate>
			<deliveryDate>2003-10-03</deliveryDate>
			<deliveryDayOfWeek>6</deliveryDayOfWeek>
			<nextDayAM>false</nextDayAM>
			<packingID>P_0</packingID>
		</product>

			
		<packing>
			<packingID>P_0</packingID>
                				<box>
				<name>No1 Item Descritpion - RacingDevil.Com</name>
				<weight>1.0</weight>
				<expediterWeight>1.0</expediterWeight>
				<length>10.0</length>
				<width>10.0</width>
				<height>10.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No1 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No2 Item Descritpion - RacingDevil.Com</name>
				<weight>2.0</weight>
				<expediterWeight>2.0</expediterWeight>
				<length>20.0</length>
				<width>20.0</width>
				<height>20.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No2 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No2 Item Descritpion - RacingDevil.Com</name>
				<weight>2.0</weight>
				<expediterWeight>2.0</expediterWeight>
				<length>20.0</length>
				<width>20.0</width>
				<height>20.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No2 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No3 Item Descritpion - RacingDevil.Com</name>
				<weight>4.5</weight>
				<expediterWeight>3.0</expediterWeight>
				<length>30.0</length>
				<width>30.0</width>
				<height>30.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No3 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No3 Item Descritpion - RacingDevil.Com</name>
				<weight>4.5</weight>
				<expediterWeight>3.0</expediterWeight>
				<length>30.0</length>
				<width>30.0</width>
				<height>30.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No3 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No3 Item Descritpion - RacingDevil.Com</name>
				<weight>4.5</weight>
				<expediterWeight>3.0</expediterWeight>
				<length>30.0</length>
				<width>30.0</width>
				<height>30.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No3 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No4 Item Descritpion - RacingDevil.Com</name>
				<weight>10.66</weight>
				<expediterWeight>4.0</expediterWeight>
				<length>40.0</length>
				<width>40.0</width>
				<height>40.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No4 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No4 Item Descritpion - RacingDevil.Com</name>
				<weight>10.66</weight>
				<expediterWeight>4.0</expediterWeight>
				<length>40.0</length>
				<width>40.0</width>
				<height>40.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No4 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No4 Item Descritpion - RacingDevil.Com</name>
				<weight>10.66</weight>
				<expediterWeight>4.0</expediterWeight>
				<length>40.0</length>
				<width>40.0</width>
				<height>40.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No4 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No4 Item Descritpion - RacingDevil.Com</name>
				<weight>10.66</weight>
				<expediterWeight>4.0</expediterWeight>
				<length>40.0</length>
				<width>40.0</width>
				<height>40.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No4 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No5 Item Descritpion - RacingDevil.Com</name>
				<weight>20.83</weight>
				<expediterWeight>5.0</expediterWeight>
				<length>50.0</length>
				<width>50.0</width>
				<height>50.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No5 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No5 Item Descritpion - RacingDevil.Com</name>
				<weight>20.83</weight>
				<expediterWeight>5.0</expediterWeight>
				<length>50.0</length>
				<width>50.0</width>
				<height>50.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No5 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No5 Item Descritpion - RacingDevil.Com</name>
				<weight>20.83</weight>
				<expediterWeight>5.0</expediterWeight>
				<length>50.0</length>
				<width>50.0</width>
				<height>50.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No5 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No5 Item Descritpion - RacingDevil.Com</name>
				<weight>20.83</weight>
				<expediterWeight>5.0</expediterWeight>
				<length>50.0</length>
				<width>50.0</width>
				<height>50.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No5 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
			<box>
				<name>No5 Item Descritpion - RacingDevil.Com</name>
				<weight>20.83</weight>
				<expediterWeight>5.0</expediterWeight>
				<length>50.0</length>
				<width>50.0</width>
				<height>50.0</height>
    								<packedItem>
					<quantity>1</quantity>
					<description>No5 Item Descritpion - RacingDevil.Com</description>
				</packedItem>
  
				
			</box>
 
		</packing>

		<shippingOptions>
			<insurance>No</insurance>
			<deliveryConfirmation>Yes</deliveryConfirmation>
			<signature>No</signature>

		</shippingOptions>
	
		<comment> For major centres only. Add 1 to 3 business days for other destinations. </comment>
		
		
	</ratesAndServicesResponse>
</eparcel>
<!--END_OF_EPARCEL-->

